/**
 * Requires yocc
 */
export * from './address.resource'
export * from './cart.resource'
export * from './consent.resource'
export * from './customer-groups.resource'
export * from './export.resource'
export * from './feed.resource'
export * from './forgotten-password.resource'
export * from './future-stock.resource'
export * from './login-notification.resource'
export * from './order.resource'
export * from './payment-details.resource'
export * from './product.resource'
export * from './promotion.resource'
export * from './order-returns.resource'
export * from './save-cart.resource'
export * from './store.resource'
export * from './user.resource'
export * from './voucher.resource'
